events {
    worker_connections 1024;
}

http {
    upstream active_app {
        # This points to blue initially
        # We change this to green during switch
        server blue:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://active_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://active_app/health;
        }
    }
}